default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-yaml
      stages: [commit]
    - id: check-json
      stages: [commit]
    - id: check-toml
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    - id: check-case-conflict
      stages: [commit]
    - id: detect-private-key
      stages: [commit]
    - id: check-added-large-files          
      stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']