name: Security audit
env:
 GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
on:
  pull_request:
    paths: '**/Cargo.lock'
  push:
    branches: master
    paths: '**/Cargo.lock'
  schedule:
    - cron: "0 0 * * *"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.TOKEN }}
