name: Daily security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  daily_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.TOKEN }}
